### PR TITLE
jpeg screenshots and call shortcut

### PR DESCRIPTION
**Pull request by mynameisv**
Hi,
Here is a new proposal : jpeg screenshots and call shortcut.
Jpeg can be usefull, 'cause sometimes, bandwith is you enemy and dirty low-ratio jpeg can do the job.

The module works like previously but with an optional parameter : Ratio for jpeg compression.
I also added a shortcut for the screenshot call, directly in the Agent Menu.

I hope this time you won't have to rewrite my code ;-)

Tests done :
(Empire: AAA...) > sc
(Empire: AAA...) > sc 10
(Empire: AAA...) > sc 90
(Empire: AAA...) > sc 150
(Empire: AAA...) > sc -1
(Empire: AAA...) > sc n00b
(Empire: AAA...) > sc 

(Empire: collection/screenshot) > reload
(Empire: collection/screenshot) > set Agent  AAA...
(Empire: collection/screenshot) > run
(Empire: collection/screenshot) > set Ratio 5
(Empire: collection/screenshot) > run
(Empire: collection/screenshot) > set Ratio 90
(Empire: collection/screenshot) > run
(Empire: collection/screenshot) > set Ratio 150
(Empire: collection/screenshot) > run
(Empire: collection/screenshot) > set Ratio -1
(Empire: collection/screenshot) > run
(Empire: collection/screenshot) > set Ratio n00b
(Empire: collection/screenshot) > run

### CODE REVIEW

**Comment by HarmJ0y** [comment]
Cool stuff man! We're about to push a branch that we've been working on which will cause a merge conflict just in lib/common/empire.py. After we push, would you mind resubmitting to dev? Should be an easy change.

**Comment by mynameisv** [comment]
ok, i'll do that

**Comment by HarmJ0y** [comment]
Cool, we'll get the other branch and pushed in the next day and will let you know here.

**Comment by HarmJ0y** [comment]
The changes are pushed to the dev branch https://github.com/powershellempire/Empire/tree/dev

You should just had to re-add the sc command to lib/common/empire.py, and modify or resubmit the PR.

**Comment by HarmJ0y** [comment]
Also, are you able to submit this to the dev branch instead of master? Thanks.

**Comment by mynameisv** [comment]
Yes i can :-)

**Comment by HarmJ0y** [comment]
FYI we're going to be dropping the Empire 1.5 release by Friday, so this will have to be integrated into the next release if it's resubmitted before then.

**Pull request closed without merging**
