### PR TITLE
Adding credentials module to extract the current interactive user's Credential Manager credentials.

### PR DESCRIPTION
**Pull request by BeetleChunks**
This module allows for plaintext credential extraction for the current interactive user. It dumps the plaintext generic credentials from the Credential Manager Store. Although these credentials are stored in Windows Vault, a non privileged user can access their own credentials, so this module can be run to extract passwords for the current interactive user. An elevated user context is not needed.

### CODE REVIEW

**Comment by HarmJ0y** [comment]
Is this something that a module in Mimikatz can't already do?

**Comment by BeetleChunks** [comment]
No, mimikatz currently does not have the ability to extract these types of passwords in an unprivileged context, they must be in an elevated context as they are pulling from memory. This module can run in any user context to extract the current interactive user's passwords. I have tested the mimikatz logonpasswords module and the vault credentials module in the same unprivileged context and they both fail giving an error message that they must be ran in an elevated context, while this one has no problems.

**Comment by BeetleChunks** [comment]
empire_module_no_need_admin

**Comment by BeetleChunks** [comment]
empire_module_no_need_admin

**Pull request merged**
