### PR TITLE
Added Hashdump using Invoke-DCSync

### PR DESCRIPTION
**Pull request by monoxgas**
This code belongs here more than anywhere else. I suck at writing modules, but hopefully this is a good starting point. Feel free to reorganize/rename as needed.

<3
-Nick

### CODE REVIEW

**Comment by HarmJ0y** [comment]
W00t, working on my end. Two small requested tweaks-> can you rename dcsync-hashdump.py to "dcsync_hashdump.py" and capitalize the arguments (computers/domain/etc.)? Otherwise the functionality looks like it works like a charm!

**Comment by monoxgas** [comment]
Fixed.

**Comment by HarmJ0y** [comment]
Cool, last thing- the related capitalizations need to be tweaked for lines 94, 97, 100, 103, then will merge.

**Comment by monoxgas** [comment]
Psh.. I totally noticed that, just wanted to see if you were paying attention

**Comment by HarmJ0y** [comment]
what_you_got

**Pull request merged**
