### PR TITLE
Powershell ICMP backup comm channel

### PR DESCRIPTION
**Pull request by spivi**
This pull request add an execution of an covert icmp channel.
This helped me a lot during my last pentests - I create a backup communication channel based on ICMP so that if my agent becomes stale, I can address the ICMP channel and launch a new one.

The client side is based on the ICMP shell from the nishang project and the icmp server on the attacker is the icmpsh_m.py module which is part of the icmpsh project.

### CODE REVIEW

**Comment by HarmJ0y** [comment]
This looks interesting, thoughts @enigma0x3 ?

**Comment by enigma0x3** [comment]
I like the idea, will definitely check it out!

**Comment by enigma0x3** [comment]
Hey @spivi,
I plan on checking this out this week (hacker summer camp got in the way of things).

Thanks for your patience!

**Comment by HarmJ0y** [comment]
At this point we're not going to merge, as the channel is completely separate from Empire's normal comms and doesn't utilize Empire's crypto (or any crypto) to protect the command execution. Listeners are being modularized in 2.0, so we can possibly readdress this type of integration once the merge happens in a few weeks.

**Pull request closed without merging**
